### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [october8ai/GTMTag#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation link [http://www.blackcrow.ai/sample_integration_documentation](http://www.blackcrow.ai/sample_integration_documentation) provided in the manifest file is not valid. Please provide valid url.
![Screenshot 2020-10-29 at 1 31 40 PM](https://user-images.githubusercontent.com/53495700/97629654-a0c1da80-19eb-11eb-8119-317765edded4.png)

**Comment by raymondborkowski** [comment]
Updated, please let me know @praveena-pappu if there are any other issues.
